### ISSUE TITLE
Incorrect encoding

### ISSUE THREAD

**Issue by KarelWintersky** [SlaSerX/PHP-Server-Status#2]
еЏ–еѕ—еЏ‚ж•°еЂј FreeBSD
зЎ®е®љж‰§иЎЊж–‡д»¶дЅЌзЅ® FreeBSD
ж‰§иЎЊзі»з»џе‘Ѕд»¤ FreeBSD
windowsзі»з»џжЋўжµ‹
жЇ”дѕ‹жќЎ
е€¤ж–­е†…е­е¦‚жћње°ЏдєЋ1GпјЊе°±жѕз¤єMпјЊеђ¦е€™жѕз¤єGеЌ•дЅЌ
зЅ‘еЌЎжµЃй‡Џ

and so on

I can't decode it.

**Comment by SlaSerX** [comment]
Try cp1251 font

На пн, 3.12.2018 г., 21:45 Karel Wintersky <notifications@github.com написа:

**Comment by SlaSerX** [comment]
Or set charset cp1251

На ср, 5.12.2018 г., 10:45 Ivan Bachvarov <slaserx3@gmail.com написа:

**Comment by KarelWintersky** [comment]
you saved and commited file as **UTF8**
